### ISSUE TITLE
ch-image pull destination error (cc version 0.27)

### ISSUE THREAD

**Issue by MandMarc** [hpc/charliecloud#1335] opened 2022-04-27 16:47 UTC
When using ch-image pull command to pull a docker image from my gitlab container registry I get the following error:

ch-image pull <gitlab_url> $HOME/ph/images
pulling image:    <gitlab_url>
requesting arch:  amd64
destination:      $HOME/ph/images

Username: <user>
Password:
manifest list: downloading: 100%
warning: image is architecture-unaware
warning: requested arch is amd64; using --arch=yolo
manifest: downloading: 100%
config: downloading: 100%
layer 1/10: 1fe172e: using existing file
layer 2/10: a7abea6: using existing file
layer 3/10: e174643: using existing file
layer 4/10: ec3120f: downloading: 13.6/13.6 MiB (100%)
layer 5/10: a15ea27: downloading: 100%
layer 6/10: f77ea77: downloading: 100%
layer 7/10: 1dea0b2: downloading: 100%
layer 8/10: e5314e3: downloading: 100%
layer 9/10: abd9848: downloading: 887.4/887.4 MiB (100%)
layer 10/10: 00549a6: downloading: 100%
flattening image
error: can't flatten: $HOME/ph/images exists but does not appear to be an image

When just using "ch-image pull <gitlab_url>", i.e. without specifying the destination, everything works and the flattened image is stored in the default storage path. It seems that the command expects the destination to be the image which is yet to be created in the specified directory. Obviously, the destination directory is itself not the image which get pulled into it. Looks like (not too complicated) bug to me.

**Comment by reidpr** [comment] 2022-05-05 21:23
Hello, thanks for the fine bug report!

The problem here is that Charliecloud wants the directory containing the image itself, not the parent directory. So here you would say `ch-image pull <gitlab_url> $HOME/ph/images/myimage`; i.e., you are correct, "the command expects the destination to be the image which is yet to be created in the specified directory", which is the intended behavior.

This looks like a similar issue to #1299. I wonder if a similar FAQ/hint would be helpful.

**Comment by reidpr** [comment] 2022-05-27 23:36
The ability to pull directly to a directly went away in PR #1255. Issue #1353 is to bring it back, and I've noted there the usability concern described here needs to be address. I'm going to close this issue as moot, but that doesn't mean we've forgotten it.

**Closed by reidpr** 2022-05-27 23:36 UTC
Labels: bug, medium, image, usability
