### ISSUE TITLE
docs: explain how to deal with non-x86 systems

### ISSUE THREAD

**Issue by loveshack** [hpc/charliecloud#1016] opened 2021-03-29 14:28 UTC
I'm running on ppc64le, and spent some time trying to find out why ch-image always pulls an x86_64 image and what to do about it (not being very familiar with docker).  I couldn't see any documentation hint about that, which I think is needed.

I found that it works to prepend ppc64le/ to the FROM argument in the Dockerfile (assuming the ppc64le version exists on the hub). I modified the code in build.py to prepend an architecture prefix to base_ref.path so that the right thing gets pulled, but I don't know if that's the appropriate fix.  You're welcome to the patch if it is OK, of course.

**Comment by reidpr** [comment] 2021-03-29 21:19
Thanks Dave; this is definitely a problem. We are working on making `ch-image` smarter about architectures. See e.g. PR #865 (I think we may close this one and re-work it) and issue #1017 (which is similar but not a duplicate). If that starts to drag then yes I agree we need to document the workaround.

**Comment by reidpr** [comment] 2021-05-21 20:09
Closing because issue #1017 is getting close and will address the root cause.

**Closed by reidpr** 2021-05-21 20:09 UTC
Labels: bug, doc, medium
