### ISSUE TITLE
Update Documentation with CentOS fix 

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#311] opened 2018-12-11 21:37 UTC
@SyraD provided a solution for #97, but it has not yet been added to the documentation. It should definitely be added to https://github.com/hpc/charliecloud/blob/master/doc-src/install.rst. Should it be added to the FAQ as well?

**Comment by reidpr** [comment] 2019-01-24 23:30
I think this is a duplicate of #97.

**Closed by reidpr** 2019-01-24 23:30 UTC
Labels: bug
