### ISSUE TITLE
Bind at build time

### ISSUE THREAD

**Issue by qwofford** [hpc/charliecloud#931] opened 2020-12-17 21:14 UTC
I would like to use a binding option at build time to make ssh keys available during Dockerfile script execution.

`ch-grow build --bind ...`

I see this is in master branch but not in v.20

Consider this "issue" as the applause before a rock concert.

**Comment by qwofford** [comment] 2020-12-17 22:14
Here's an example of what I like in master that is not in v0.20:


Master has a bind option:
```
(base) bash-4.2$ ./ch-grow build --help
usage: ch-image build [-h] [-b SRC[:DST]] [--build-arg ARG[=VAL]]
                      [-f DOCKERFILE] [--force] [-n] [--no-force-detect]
                      [--parse-only] [-t TAG]
                      CONTEXT

build image from Dockerfile

positional arguments:
  CONTEXT                context directory

optional arguments:
  -h, --help             show this help message and exit
  -b, --bind SRC[:DST]   mount SRC at guest DST (default /mnt/0, /mnt/1, etc.)
  --build-arg ARG[=VAL]  set build-time variable ARG to VAL, or $ARG if no VAL
  -f, --file DOCKERFILE  Dockerfile to use (default: CONTEXT/Dockerfile)
  --force                inject unprivileged build workarounds
  -n, --dry-run          don't execute instructions
  --no-force-detect      don't try to detect if --force workarounds would work
  --parse-only           stop after parsing the Dockerfile
  -t, --tag TAG          name of image to create (default: inferred)

(base) bash-4.2$ ./ch-grow --version
0.21~pre+d4ef02a
```
v.20 does not have a bind option:
```
(base) bash-4.2$ ch-grow build --help
usage: ch-grow build [-h] [--build-arg ARG[=VAL]] [-f DOCKERFILE] [-n]
                     [--no-fakeroot] [--parse-only] [-t TAG]
                     CONTEXT

build image from Dockerfile

positional arguments:
  CONTEXT                context directory

optional arguments:
  -h, --help             show this help message and exit
  --build-arg ARG[=VAL]  set build-time variable ARG to VAL, or $ARG if no VAL
  -f, --file DOCKERFILE  Dockerfile to use (default: CONTEXT/Dockerfile)
  -n, --dry-run          don't execute instructions
  --no-fakeroot          don't try unprivileged build workarounds
  --parse-only           stop after parsing the Dockerfile
  -t, --tag TAG          name of image to create (default: inferred)
(base) bash-4.2$ ch-grow --version
0.20
```

**Comment by reidpr** [comment] 2020-12-17 22:40
I think this is a duplicate of PR #891, which as you note should be in 0.21, hopefully out in a few days. Thanks!

**Closed by reidpr** 2020-12-17 22:40 UTC
