### ISSUE TITLE
Released tarballs can not be built

### ISSUE THREAD

**Issue by olifre** [hpc/charliecloud#46] opened 2017-10-27 00:56 UTC
```
$ make
make: *** No rule to make target 'VERSION.full', needed by 'all'.  Stop.
```
The tarballs in github-released do not contain `.git`, so there's no rule to create `VERSION.full`.
```
$ echo "0.2.2" > VERSION.full
```
resolves that, but of course that's not really ideal.

**Comment by reidpr** [comment] 2017-10-27 15:45
I definitely agree this is a bug! It's a duplicate of #33, though, where you can find more detail about what's going on.

**Closed by reidpr** 2017-10-27 15:45 UTC

**Comment by olifre** [comment] 2017-10-27 15:53
Ah, yes, of course!
I totally missed that one since I just saw `.zip` in the subject and used `.tar.gz` or `tarball` as patterns to look for in my head. Sorry for that!
