### ISSUE TITLE
No error message for 'make' Charliecloud

### ISSUE THREAD

**Issue by epanas** [hpc/charliecloud#505] opened 2019-08-06 20:10 UTC
```
$ git clone --recursive git@git.lanl.gov:reidpr/charliecloud.git
$ cd charliecloud/test
$ make where-bats
which bats
/home/epanas/charliecloud/test/bats/bin/bats
bats --version
Bats 0.4.0
$ export CH_TEST_TARDIR=/var/tmp/tarballs
$ export CH_TEST_IMGDIR=/var/tmp/images
$ export CH_TEST_PERMDIRS='/var/tmp/tmp'
$ make test
./make-auto build chtest/Build Build.missing Dockerfile.alpine36 Dockerfile.alpineedge Dockerfile.centos6 Dockerfile.centos7 Dockerfile.debian9 Dockerfile.nvidia Dockerfile.openmpi Dockerfile.python3 Dockerfile.ubuntu1604 Docker_Pull.alpine36_dp ../examples/mpi/lammps/Dockerfile ../examples/mpi/mpibench/Dockerfile ../examples/mpi/mpihello/Dockerfile ../examples/mpi/paraview/Dockerfile ../examples/other/spark/Dockerfile ../examples/serial/hello/Dockerfile > build_auto.bats
bats build.bats build_auto.bats build_post.bats
/home/epanas/charliecloud/test/bats/libexec/bats-exec-suite: line 20: let: count+=: syntax error: operand expected (error token is "+=")
Makefile:24: recipe for target 'test-build' failed
make: *** [test-build] Error 1
$ make test-build
bats build.bats build_auto.bats build_post.bats
/home/epanas/charliecloud/test/bats/libexec/bats-exec-suite: line 20: let: count+=: syntax error: operand expected (error token is "+=")
Makefile:24: recipe for target 'test-build' failed
make: *** [test-build] Error 1
```
The expectation is for `$ make test` to run the tests in charliecloud and show whether or not these tests failed but instead I was given the error value 1 which does not tell me what to do in order to fix this error. A more meaningful error message could have given me more detail to proceed since the real error was that charliecloud was not made yet aka `make`. This should be fixed to lessen confusion. Thanks.

**Comment by reidpr** [comment] 2019-08-19 15:29
Turns out this is a duplicate of #329, so closing. But we may now be able to make meaningful progress on it!

**Closed by reidpr** 2019-08-19 15:29 UTC
Labels: bug
