### ISSUE TITLE
Issues with `ch-fromhost --nvidia` shared library injection (symlink error)

### ISSUE THREAD

**Issue by seantrons** [hpc/charliecloud#1706] opened 2023-08-17 15:08 UTC
## Summary
Recently, I've been working with Nvidia's TAO containers which are available on the company's public registry, nvcr.io. When working with this images on a cluster using Charliecloud, I noticed that I was finding a lot of errors related to missing shared libraries/dependencies and so I started on some detective work. I rebuilt the images from scratch and re-ran the `ch-fromhost --nvidia --verbose <container-name>` command and noticed an error that I glossed over the first time around, shown below:
![image](https://github.com/hpc/charliecloud/assets/142455901/588f44fd-25cd-4444-8ea9-0407485c98bb)

After doing some digging and speaking with @reidpr in a charliecloud forum, I learned this was caused by broken symlink. The link was invalid on the host machine, but valid relative to the container as seen below: 
![image](https://github.com/hpc/charliecloud/assets/142455901/a6f0c4df-1cbd-460d-befe-1834393cf021)

For a temporary work around, I went into the container (directory format) to rename the symlink (`lib` to `lib.bak`) and create an actually directory in its place. Re-running the `ch-fromhost --nvidia <container-name>` command, I was then able to successfully inject the necessary shared libraries. 

## Steps to Reproduce
1. `ch-image pull nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf1.15.5 tao-tf1`
2. `ch-convert tao-tf1 ./tao-tf1-container`
3. `ch-fromhost --nvidia --verbse ./tao-tf1-container`
4. `ch-run -w ./tao-tf1-container nvidia-smi` 

Following the steps above, I was given errors related to the application not being able to find the required libnvidia-ml.so and libcuda.so libraries.

## Environment
- All steps were run on an nvidia gpu enabled node with the necessary drivers installed
- Charliecloud version: 0.33

**Comment by reidpr** [comment] 2024-01-22 23:40
I can't reproduce this. I see the "No such file or directory" warnings, but that's #732 I think. I do not see the "not a symbolic link" errors.

@seantrons, is this still a problem for you?

**Comment by reidpr** [comment] 2024-02-01 21:34
Closing as WORKSFORME. Please re-open if this is an error.

**Closed by reidpr** 2024-02-01 21:34 UTC
Labels: bug, worksforme, high, image, glue
