### ISSUE TITLE
0.26: 90 second tutorial error "appstream... No URLs in mirrorlist"

### ISSUE THREAD

**Issue by hpcpony** [hpc/charliecloud#1298] opened 2022-03-05 19:57 UTC
Pretty much just doing what's in the tutorial at https://hpc.github.io/charliecloud/tutorial.html#seconds-to-charliecloud.

```
[user@host hello]$ ch-image build --force .
inferred image name: hello
  2 FROM centos:8
manifest list: downloading: 100%
manifest: downloading: 100%
config: downloading: 100%
layer 1/1: a1d0c75: downloading: 79.6/79.6 MiB (100%)
flattening image
layer 1/1: a1d0c75: listing
validating tarball members
resolving whiteouts
layer 1/1: a1d0c75: extracting
image arch: amd64
will use --force: rhel8: CentOS/RHEL 8+
  4 RUN ['/bin/sh', '-c', 'dnf install -y --setopt=install_weak_deps=false openssh-clients  && dnf clean all']
workarounds: init step 1: checking: $ command -v fakeroot > /dev/null
workarounds: init step 1: $ set -ex; if ! grep -Eq '\[epel\]' /etc/yum.conf /etc/yum.repos.d/*; then dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm; dnf install -y fakeroot; dnf remove -y epel-release; else dnf install -y fakeroot; fi;
+ grep -Eq '\[epel\]' /etc/yum.conf /etc/yum.repos.d/CentOS-Linux-AppStream.repo /etc/yum.repos.d/CentOS-Linux-BaseOS.repo /etc/yum.repos.d/CentOS-Linux-ContinuousRelease.repo /etc/yum.repos.d/CentOS-Linux-Debuginfo.repo /etc/yum.repos.d/CentOS-Linux-Devel.repo /etc/yum.repos.d/CentOS-Linux-Extras.repo /etc/yum.repos.d/CentOS-Linux-FastTrack.repo /etc/yum.repos.d/CentOS-Linux-HighAvailability.repo /etc/yum.repos.d/CentOS-Linux-Media.repo /etc/yum.repos.d/CentOS-Linux-Plus.repo /etc/yum.repos.d/CentOS-Linux-PowerTools.repo /etc/yum.repos.d/CentOS-Linux-Sources.repo
+ dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
CentOS Linux 8 - AppStream                                                            202  B/s |  38  B     00:00
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
error: command failed with code 1: /opt/charliecloud-0.26/bin/ch-run
```

**Comment by reidpr** [comment] 2022-03-07 22:15
Thanks for the report. This is due to CentOS 8 repositories shutting down. Looks like a duplicate of #1288.

The specific fix for the hello example is [here](https://github.com/hpc/charliecloud/commit/8f2cb30f29d1a6b975e86a2de8d377562ed9e3ad#diff-4e0c3624bf083963b02aee447ec8793f0868bc1fedb5f4d86e2582e3c69b341e) if it helps. You could also likely swap in `almalinux:8` or `rockylinux:8`.

**Closed by reidpr** 2022-03-07 22:15 UTC
Labels: bug, duplicate, medium, test
